-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."EmployerVerifications"
(
    "EmployerId" integer NOT NULL,
    "EmailVerification" boolean NOT NULL,
    "SystemPersonalVerification" boolean NOT NULL,
    PRIMARY KEY ("EmployerId")
);

CREATE TABLE IF NOT EXISTS public."Employers"
(
    "EmployerId" integer NOT NULL,
    "CompanyName" character varying[] NOT NULL,
    "PhoneNumber" character varying[] NOT NULL,
    "WebSite" character varying[] NOT NULL,
    PRIMARY KEY ("EmployerId")
);

CREATE TABLE IF NOT EXISTS public."JobPositions"
(
    "JobPositionId" integer NOT NULL,
    "JobPositionTitle" character varying[] NOT NULL,
    "UserId" integer NOT NULL,
    PRIMARY KEY ("JobPositionId")
);

CREATE TABLE IF NOT EXISTS public."JobSeekers"
(
    "JobSeekerId" integer NOT NULL,
    "FirstName" character varying[] NOT NULL,
    "LastName" character varying[] NOT NULL,
    "NationalityId" character varying(11)[] NOT NULL,
    "YearOfBirth" character varying(4)[] NOT NULL,
    PRIMARY KEY ("JobSeekerId")
);

CREATE TABLE IF NOT EXISTS public."SystemPersonal"
(
    "SystemPersonalId" integer NOT NULL,
    "SystemPersonalName" character varying[] NOT NULL,
    "SystemPersonalLastName" character varying[] NOT NULL,
    "Authority" character varying[] NOT NULL,
    PRIMARY KEY ("SystemPersonalId")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL,
    "Email" character varying(50)[] NOT NULL,
    "Password" character varying(20)[] NOT NULL,
    "RePassword" character varying(20)[] NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users_JobSeekers"
(
    "Users_Id" integer NOT NULL,
    "JobSeekers_JobSeekerId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Users_Employers"
(
    "Users_Id" integer NOT NULL,
    "Employers_EmployerId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Users_SystemPersonal"
(
    "Users_Id" integer NOT NULL,
    "SystemPersonal_SystemPersonalId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Users_JobPositions"
(
    "Users_Id" integer NOT NULL,
    "JobPositions_UserId" integer NOT NULL
);

ALTER TABLE public."Users_JobSeekers"
    ADD FOREIGN KEY ("Users_Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Users_JobSeekers"
    ADD FOREIGN KEY ("JobSeekers_JobSeekerId")
    REFERENCES public."JobSeekers" ("JobSeekerId")
    NOT VALID;


ALTER TABLE public."Users_Employers"
    ADD FOREIGN KEY ("Users_Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Users_Employers"
    ADD FOREIGN KEY ("Employers_EmployerId")
    REFERENCES public."Employers" ("EmployerId")
    NOT VALID;


ALTER TABLE public."Users_SystemPersonal"
    ADD FOREIGN KEY ("Users_Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Users_SystemPersonal"
    ADD FOREIGN KEY ("SystemPersonal_SystemPersonalId")
    REFERENCES public."SystemPersonal" ("SystemPersonalId")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("EmployerId")
    REFERENCES public."EmployerVerifications" ("EmployerId")
    NOT VALID;


ALTER TABLE public."Users_JobPositions"
    ADD FOREIGN KEY ("Users_Id")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Users_JobPositions"
    ADD FOREIGN KEY ("JobPositions_UserId")
    REFERENCES public."JobPositions" ("UserId")
    NOT VALID;

END;